sudo: required
services:
  - docker

before_install:
  - docker build -t docker590/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run docker590/react-test npm run test -- --coverage

after_success:
  - docker build -t docker590/multi-client ./client
  - docker build -t docker590/multi-nginx ./nginx
  - docker build -t docker590/multi-server ./server
  - docker build -t docker590/multi-worker ./worker

  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  - docker push docker590/multi-client
  - docker push docker590/multi-nginx
  - docker push docker590/multi-server
  - docker push docker590/multi-worker
